// flow-typed signature: d25dfc8d6f05a6e549bafaead5548be8
// flow-typed version: <<STUB>>/react-cosmos-webpack_v^2.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cosmos-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cosmos-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cosmos-webpack/bin/cosmos-export' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/bin/cosmos' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/default-webpack-config' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/export' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/loader-entry' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/loader-webpack-config' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/module-loader' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/normalize-modules' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/server' {
  declare module.exports: any;
}

declare module 'react-cosmos-webpack/lib/user-modules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cosmos-webpack/bin/cosmos-export.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/bin/cosmos-export'>;
}
declare module 'react-cosmos-webpack/bin/cosmos.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/bin/cosmos'>;
}
declare module 'react-cosmos-webpack/lib/default-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/default-webpack-config'>;
}
declare module 'react-cosmos-webpack/lib/export.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/export'>;
}
declare module 'react-cosmos-webpack/lib/loader-entry.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/loader-entry'>;
}
declare module 'react-cosmos-webpack/lib/loader-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/loader-webpack-config'>;
}
declare module 'react-cosmos-webpack/lib/module-loader.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/module-loader'>;
}
declare module 'react-cosmos-webpack/lib/normalize-modules.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/normalize-modules'>;
}
declare module 'react-cosmos-webpack/lib/server.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/server'>;
}
declare module 'react-cosmos-webpack/lib/user-modules.js' {
  declare module.exports: $Exports<'react-cosmos-webpack/lib/user-modules'>;
}
